version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: globeclicker-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - globeclicker-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: globeclicker-backend
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://admin:password123@globeclicker-mongodb:27017/globalclicker?authSource=admin
      - PORT=5001
    depends_on:
      - mongodb
    networks:
      - globeclicker-network

volumes:
  mongodb_data:

networks:
  globeclicker-network:
    driver: bridge 